zone-parameters:
  syncTime: 10s

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/moz_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      maximum-pool-size: 4