endpoint:
  inflation: '/cosmos/mint/v1beta1/inflation'
  active-validators-quantity: '/cosmos/base/tendermint/v1beta1/validatorsets/latest'
  active-validators-quantity-legacy: '/validatorsets/latest'
  active-validators-quantity-extra: '/cosmos/staking/v1beta1/validators?status=BOND_STATUS_BONDED&pagination.limit=1&pagination.count_total=true'
  all-validators-quantity: '/cosmos/staking/v1beta1/validators?pagination.limit=1&pagination.count_total=true'
  active-validator-list: '/cosmos/staking/v1beta1/validators?status=BOND_STATUS_BONDED&pagination.limit=200'
  all-validator-list: '/cosmos/staking/v1beta1/validators?pagination.limit=1000'
  amount-of-bonded: '/cosmos/staking/v1beta1/pool'
  unbound-period: '/cosmos/staking/v1beta1/params'
  supply: '/cosmos/bank/v1beta1/supply/%s'
  delegations: '/cosmos/staking/v1beta1/validators/%s/delegations?pagination.limit=1000000'
  undelegations: '/cosmos/staking/v1beta1/validators/%s/unbonding_delegations?pagination.limit=1000000'
  validator-param: '/cosmos/staking/v1beta1/validators/%s'

spring:
  main:
    web-application-type: none

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: SKIP
        jdbc:
          lob:
            non_contextual_creation: true